apiVersion: v1
kind: Secret
metadata:
  name: minio-spark-secret
  namespace: processing
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "your_acess_key_id"
  AWS_SECRET_ACCESS_KEY: "your_secret_acess_key"
